theme: jekyll-theme-chirpy
title: My Chirpy Blog
description: A blog fully deployed via GitHub Actions
baseurl: ""
url: "https://chamalgomeshso.github.io"
# github:
#   repository_url: https://github.com/chamalgomeshso/hosted-blog
