theme: jekyll-theme-chirpy
title: My Chirpy Blog
tagline: A simple blog # it will display as the subtitle
description: >- # used by seo meta and the atom feed
   A blog fully deployed via GitHub Actions.
  
baseurl: "/hosted-blog"
url: "https://chamalgomeshso.github.io"
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor
# github:
#   repository_url: https://github.com/chamalgomeshso/hosted-blog
